import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
    paddingBottom: 3,
    borderBottomWidth: 1.5,
    borderBottomColor: "#0369a1",
  },
  profileSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  imageContainer: {
    width: 48,
    height: 48,
    borderWidth: 1.5,
    borderColor: "#0369a1",
    borderRadius: 24,
    overflow: "hidden",
  },
  profileImage: {
    width: 72,
    height: 50,
    position: "absolute",
    top: -2,
    left: -12,
  },
  name: {
    fontSize: 17,
    fontFamily: "Helvetica-Bold",
    color: "#111827",
    letterSpacing: -0.3,
  },
  role: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: "#0369a1",
    marginTop: 1,
  },
  contactSection: {
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "center",
    minWidth: 180,
  },
  contactItem: {
    fontSize: 8.5,
    fontFamily: "Helvetica",
    color: "#4b5563",
    marginBottom: 1,
    lineHeight: 1.2,
  },
  contactRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 1,
  },
  contactLabel: {
    width: 46,
    fontSize: 8.5,
    fontFamily: "Helvetica-Bold",
    color: "#4b5563",
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: "#0369a1",
    marginBottom: 0,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  title: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: "#111827",
    marginBottom: 0,
  },
  subtitle: {
    fontSize: 8.5,
    fontFamily: "Helvetica-Oblique",
    color: "#6b7280",
    marginBottom: 0.5,
  },
  contentText: {
    fontSize: 9,
    fontFamily: "Helvetica",
    color: "#374151",
    marginLeft: 4,
    marginBottom: 0.5,
    lineHeight: 1.3,
  },
  skillGroup: {
    flex: "1 0 48%",
    marginBottom: 1,
  },
  chipContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 2,
  },
  chip: {
    backgroundColor: "#f0f9ff",
    borderRadius: 3,
    paddingVertical: 1,
    paddingHorizontal: 4,
    fontSize: 7.5,
    fontFamily: "Helvetica",
    color: "#0c4a6e",
    borderWidth: 0.5,
    borderColor: "#bae6fd",
  },
  contactLink: {
    fontSize: 8.5,
    fontFamily: "Helvetica",
    color: "#0369a1",
    textDecoration: "none",
  },
  container: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    paddingTop: 1,
  },
  sectionWrapper: {
    marginBottom: 3,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 1.5,
  },
  sectionDivider: {
    flex: 1,
    height: 1,
    backgroundColor: "#d1d5db",
  },
});
